drop table if exists onepiece;
create table onepiece
(
    id integer generated by default as identity primary key,
    name varchar(100) ,
    description varchar(200) ,
    flag varchar(100)
);

--insert into onepiece(id,name,description,flag)
--values
--(1,'Luffy','Monkey D. Luffy, Devil fruit: gum gum fruit, Emperor of the sea','StrawHat Pirates');
--(2,'Law','Trafalger D. Law, Devil fruit: revive revive fruit, doctor/swordsmen','Heart Pirates');
--(3,'Roger','Gol D Roger, Devil fruit: none, King of the Pirates','The Roger Pirates');
